[package]
name = "aquila"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
surge-ping = "0.8"
netneighbours = "0.1.2"
macaddr = "1.0"
chrono = "0.4.43"
ipnet = "2.11.0"